include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build

build software:
  extends: .container-builder
  stage: build
  variables:
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/mvapich2_osu:2_5.9_cuda_haswell
    DOCKERFILE: ci/mvapich2_osu_cuda/Dockerfile
