include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build

build haswell:
  extends: .container-builder
  stage: build
  variables:
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/mpich_osu:3.4.3_6.0_haswell
    DOCKERFILE: ci/mpich_osu/Dockerfile
    DOCKER_BUILD_ARGS: '["TARGET=haswell"]'


build zen2:
  extends: .container-builder
  stage: build
  variables:
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/mpich_osu:3.4.3_6.0_zen2
    DOCKERFILE: ci/mpich_osu/Dockerfile
    DOCKER_BUILD_ARGS: '["TARGET=zen2"]'
