include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build_base
  - build
  - test

build base:
  extends: .container-builder-dynamic-name
  stage: build_base
  variables:
    WATCH_FILECHANGES: ci/docker/Dockerfile.base
    DOCKERFILE: ci/docker/Dockerfile.base
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/base/hello_world_base

build software:
  extends: .container-builder
  stage: build
  variables:
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/hello_world:03-$CI_COMMIT_SHORT_SHA
    DOCKERFILE: ci/docker/Dockerfile
    DOCKER_BUILD_ARGS: '["BASEIMG=$BASE_IMAGE"]'

test software:
  extends: .container-runner-daint-mc
  stage: test
  image: $CSCS_REGISTRY_PATH/hello_world:03-$CI_COMMIT_SHORT_SHA
  script:
    - /hello/bin/hello
  variables:
    SLURM_NTASKS: 4
    SLURM_JOB_NUM_NODES: 1
    SLURM_LABELIO: 1
    USE_MPI: 'YES'
