include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build

build software:
  extends: .container-builder
  stage: build
  variables:
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/mpich_osu:3.4.3_6.0_haswell
    DOCKERFILE: ci/mpich_osu/Dockerfile
